Add support for scheduled Fargate Tasks
RoundingWellOS/serverless-fargate-tasks pull request #2
Opened 2020-12-02 15:54 UTC by BenCoffeed

Add support for scheduled tasks

2020-12-02 16:58 UTC, shadowhand approved these changes
🆗 (I have no idea what I'm doing)

2020-12-02 16:58 UTC, shadowhand commented on README.md
> +        image: image: 123456789369.dkr.ecr.eu-west-1.amazonaws.com/my-image
`eu-west-1` ?

2020-12-02 17:41 UTC, dhrrgn requested changes
Just a few formatting tweaks.  I had other changes, but you already fixed though 😄 . It looks OK from a code POV... not so sure about the CloudFormation template though. 

You can always run `sls print --stackid something` to make sure everything parses correctly at least.  

You could also run `sls print --stackid something` and it will output the whole package, including the full CloudFormation template

2020-12-02 17:43 UTC, dhrrgn commented
Of course, that `sls print` / `sls package` stuff would need ran in a repo with serverless.  You could create a dummy folder in this repo with a serverless config and test it that way I guess

2020-12-02 17:44 UTC, dhrrgn commented on README.md
> +        image: image: 123456789369.dkr.ecr.eu-west-1.amazonaws.com/my-image
This is a fork of a plugin that hasn't been developed on in a year, and the original dev is in the netherlands

2020-12-02 18:25 UTC, BenCoffeed commented
Alright. This is now working as far as I can tell. I installed the branch on another project using `npm install RoundingWellOS/serverless-fargate-tasks#feature/addScheduleSupport and did a deploy. All resources appear to have been created as expected.

2020-12-02 18:30 UTC, BenCoffeed commented on README.md
> +        image: image: 123456789369.dkr.ecr.eu-west-1.amazonaws.com/my-image
Yea, so. . . I was developing a project where I wanted to convert a serverless lambda function that ran pgdump to make archives of psql databases. However, the 15 minute max timeout of the lambda function was hit rather quickly thus the desire to convert to a Fargate task. I liked the idea of a serverless plugin since it matches the CI/CD pipeline tools of our other projects and I found this plugin. However, it wasn't really designed for this sort of cron-based fargate task. It was designed for more long-running service tasks. However, I noticed that there was a PR opened a little over a year ago into the original repo, but the maintainers had gone silent. So, just for fun, I tested the deployment with my own fork of the plugin plus the `noService` option. It worked a treat. Then, while I was writing out the cloudformation code for the scheduled event in the `resources` section of the serverless.yml file, I thought "Why not just pick up our own fork of the plugin and add the scheduled event support so we can reuse it later in other projects. So. . . I did that.

2020-12-02 23:42 UTC, dhrrgn approved these changes
I could nit-pick some implementation details, but you made it consistent with the original implementation, so...not gonna do that. 

Looks good. 

:shipit:

2020-12-03 00:17 UTC, BenCoffeed commented
Yea, it took a lot of self control to not go through and change it all in this PR. Will clean that up later.

2020-12-03 00:17 UTC, merged